### ISSUE TITLE
Support RsBuild

### ISSUE THREAD

**Issue by longht021189** [eryue0220/unplugin-stylex#37]
Hi, I post a discussion in [facebook/stylex](https://github.com/facebook/stylex/discussions/568).

In discussion, I try to use `unplugin-stylex` with `RsBuild` but it's not working.

For a minimal reproduction repo, you can check here
https://github.com/longht021189/unplugin-stylex-sample/blob/main/rsbuild.config.ts

**Comment by eryue0220** [comment]
Thanks for your feedback, I've found the bug. I'll fix it later today.

**Comment by eryue0220** [comment]
Hi @longht021189 Please upgrade the `unplugin-stylex` to `0.3.1` and now it workds. Or you can also refer to [rsbuild-example](https://github.com/eryue0220/unplugin-stylex/blob/main/examples/rsbuild-example/rsbuild.config.ts). Finally, Thanks for your feedback.

**Comment by longht021189** [comment]
Hi @eryue0220 Thank you for your help, it works. But it's still have a minor issue, this is my logs.
```
[@stylexjs/babel-plugin] Expected (options.unstable_moduleResolution) to be one of
        - `null` or `undefined`
        - one of
                - an object where:
                        - Expected "type": to be the literal "commonJS"
                        - Expected "rootDir": to be a string
                        - Expected "themeFileExtension": to be  -
                                - one of
                                        - `null` or `undefined`
                                        - a string
                        - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
                - an object where:
                        - Expected "type": to be the literal "haste"
                        - Expected "themeFileExtension": to be  -
                                - one of
                                        - `null` or `undefined`
                                        - a string
                        - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
                        - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
                - an object where:
                        - Expected "type": to be the literal "experimental_crossFileParsing"
                        - Expected "rootDir": to be a string
                        - Expected "themeFileExtension": to be  -
                                - one of
                                        - `null` or `undefined`
                                        - a string
                        - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
But got: {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
```

And this is my configs
![Screenshot 2024-05-12 205825](https://github.com/eryue0220/unplugin-stylex/assets/47407870/dc3a2017-3544-4ab9-803f-bc2bf49c6a0b)

**Comment by eryue0220** [comment]
> Hi @eryue0220 Thank you for your help, it works. But it's still have a minor issue, this is my logs.
> 
> ```
> 
> [@stylexjs/babel-plugin] Expected (options.unstable_moduleResolution) to be one of
> 
>         - `null` or `undefined`
> 
>         - one of
> 
>                 - an object where:
> 
>                         - Expected "type": to be the literal "commonJS"
> 
>                         - Expected "rootDir": to be a string
> 
>                         - Expected "themeFileExtension": to be  -
> 
>                                 - one of
> 
>                                         - `null` or `undefined`
> 
>                                         - a string
> 
>                         - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
> 
>                 - an object where:
> 
>                         - Expected "type": to be the literal "haste"
> 
>                         - Expected "themeFileExtension": to be  -
> 
>                                 - one of
> 
>                                         - `null` or `undefined`
> 
>                                         - a string
> 
>                         - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
> 
>                         - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
> 
>                 - an object where:
> 
>                         - Expected "type": to be the literal "experimental_crossFileParsing"
> 
>                         - Expected "rootDir": to be a string
> 
>                         - Expected "themeFileExtension": to be  -
> 
>                                 - one of
> 
>                                         - `null` or `undefined`
> 
>                                         - a string
> 
>                         - {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
> 
> But got: {"type":"commonjs","rootDir":"C:/Users/longh/OneDrive/Desktop/Projects/superapp/apps/utilities"}
> 
> ```
> 
> 
> 
> And this is my configs
> 
> ![Screenshot 2024-05-12 205825](https://github.com/eryue0220/unplugin-stylex/assets/47407870/dc3a2017-3544-4ab9-803f-bc2bf49c6a0b)
> 
> 

Sorry for the late response, I will check this later

**Comment by eryue0220** [comment]
@longht021189 Hi, can you upgrade the config in your repo: https://github.com/longht021189/unplugin-stylex-sample/blob/main/rsbuild.config.ts

**Comment by eryue0220** [comment]
Hi @longht021189 I checked the bug, and I found the problem it's type should be set to `commonJS`, instead of `commonjs`;

**Comment by longht021189** [comment]
Sorry, I have a little busy. It's ok.
I used pnpm patch to work around this typo issue.
Thank you so much.
