### ISSUE TITLE
Webpack and RSPack plugins fail when there are files with other extensions

### ISSUE THREAD

**Issue by deepjoy** [eryue0220/unplugin-stylex#39]
When there are other file types/loaders used, an attempt is made to process them as valid input for stylex leading to a compilation failure
example if the index.html file has a different extension for template compilation.

```
ERROR in   Error: Child compilation failed:
  Module parse failed: Unexpected token (1:0)
  File was processed with these loaders:
   * ../../node_modules/.pnpm/html-webpack-plugin@5.6.0_webpack@5.91.0/node_modules/html-webpack-plugin/lib/loader.js
   * ../../node_modules/.pnpm/unplugin@1.10.1/node_modules/unplugin/dist/webpack/loaders/transform.js
  You may need an additional loader to handle the result of these loaders.
  > <!DOCTYPE html>
  | <html lang="en">
  | 
```

**Comment by eryue0220** [comment]
https://github.com/eryue0220/unplugin-stylex/releases/tag/v0.3.2

**Comment by deepjoy** [comment]
I've been runnning into this with more and more extensions since bundlers deal with fonts, images, svg, xml, json and numerous other extension. Could we flip to a model that only `validExts` are processed by this plugin. 


Maybe something like
'''
[ ".js", ".cjs", ".mjs", ".ts", ".jsx", ".tsx"]
'''
By default.
