### ISSUE TITLE
 Webpack and RSPack plugins require excluding font and other binary files

### ISSUE THREAD

**Issue by deepjoy** [eryue0220/unplugin-stylex#48]
This is a follow up to #39 
Since bundlers deal with numerous file types using a allowed list instead of a blocked list seems like it would be a good idea.

My suggestion would be to use a regex that is override-able using config.

**Comment by deepjoy** [comment]
Thanks! are you able to push a new minor/patch version to npm soon?

**Comment by deepjoy** [comment]
@eryue0220  are you able to push a new minor/patch version to npm soon?

**Comment by eryue0220** [comment]
> @eryue0220 are you able to push a new minor/patch version to npm soon?

Sorry for the late, I just published [v0.4.1](https://www.npmjs.com/package/unplugin-stylex)

**Comment by deepjoy** [comment]
@eryue0220 i don't see the latest changes in the 0.4.1 bundle on npm. Can you please confirm.

**Comment by eryue0220** [comment]
> @eryue0220 i don't see the latest changes in the 0.4.1 bundle on npm. Can you please confirm.

Sorry for the mistake, I forgot running the build before publish. 

Currently it's [0.4.2](https://www.npmjs.com/package/unplugin-stylex)
